FROM mcr.microsoft.com/dotnet/sdk:8.0 AS test
WORKDIR /src

COPY . .

RUN dotnet restore "UserAuthApi.sln"
RUN dotnet build "UserAuthApi.sln" -c Release --no-restore

ENV DOTNET_CLI_TELEMETRY_OPTOUT=1
CMD ["dotnet", "test", "UserAuthApi.sln", "-c", "Release", "--no-build", \
     "--logger", "console;verbosity=detailed", \
     "--collect", "XPlat Code Coverage", \
     "--results-directory", "/src/TestResults", \
     "--", "DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover"]
